### ISSUE TITLE
Managing extensions with Firefox works only if add-on disabled? 

### ISSUE THREAD

**Issue by gogi983** [nE0sIghT/chrome-gnome-shell-mirror#33]
Hi guys,

While having a look at my active modules in Firefox, I just noticed that "Gnome-Shell-Integration" add-on was disabled (I didn't disable it by myself for sure...). So I enabled it as it should be and figured out that I couldn't make the link when I visit the website for extensions ; but obviously it does work if I disable the add-on (of course the connector chrome-gnome-shell is installed on my laptop)?!
Is that a weird buggy behaviour or is it absolutely normal and we don't need anymore the add-on for Firefox? Please let me know.
By the way, I'm on Debian Sid and the version of : 
- chrome-gnome-shell is 8-3.
- Firefox-ESR 45.7.0esr-4

Regards.

**Comment by nE0sIghT** [comment]
Hi.

There are 2 add-ons:
- GNOME Shell integration **NPAPI plugin** which is shipped with GNOME Shell since version 3.4.<br />
It currently works with:
  - GNOME Web (Epiphany)
  - Firefox ESR <= 52
  - Firefox < 52

It will randomly crash if it's version older than 3.22.2.
You can find it under "Plugins" page.

- GNOME Shell integration **browser extension** (chrome-gnome-shell) which consists of 2 parts:
  1. native host messaging connector (usually package named "chrome-gnome-shell" in your distro)
  2. browser extension which should be installed from browser store. For Firefox it's located [here](https://addons.mozilla.org/firefox/addon/gnome-shell-integration/).<br>
It currently works with:
  - Firefox >= 50
  - Chrome/Chromium
  - Opera
  - Vivaldi

If you have both installed and enabled on supported browser, than you will use **browser extension** (no plugin icon will be shown at address bar).
If you do not have **browser extension** or it is disabled, than website will try to load **NPAPI plugin**. You will receive some confirmation dialog and you will get plugin icon at address bar. If you will allow to always load **NPAPI plugin** than you can refresh website page and it should work as expected.

Since you are using Firefox ESR 45, then you can not use **browser extension**.

**Comment by gogi983** [comment]
Hi,

I have to apologize, my bad sorry, as in fact you're right the extension
is shipped under "Plugins" for versions <=52...

This is due to the fact that I used to work with Firefox version from
Sid & Experimental repos until few days ago... :-[

Thread closed as far as I'm concerned.

Regards.

*Goran LAZAREVIC*
