### ISSUE TITLE
Migrate from jQuery 2.1.4 to 3

### ISSUE THREAD

**Issue by vanillajonathan** [nE0sIghT/chrome-gnome-shell-mirror#40]
Migrate from the old jQuery 2.1.4 to the new jQuery 3.1.1.
Perhaps the slim build could be used?

Relevant link is the upgrade guide:
https://jquery.com/upgrade-guide/3.0/

It should also be considered to drop jQuery entirely in favor of pure JavaScript.

**Comment by nE0sIghT** [comment]
Why?

**Comment by vanillajonathan** [comment]
The jQuery 2 branch is EOL and no longer maintained, hence it makes sense to upgrade to jQuery 3 which is actively developed and maintained.

Migration should be pretty smooth, sometimes some small code modifications is needed, sometimes no changes are needed.

When going to jQuery 3 the slim build should be considered since it is smaller. It drops support for Ajax and animations. The extension uses animations but that could probably be dropped.

A strong reason to use jQuery is for its broad compatibility to develop sites to target legacy browser in an easy way without conditional code for implementations in different browsers. But with a web browser extension you know it will be executed in a modern environment hence using jQuery is less compelling.

**Comment by nE0sIghT** [comment]
> The jQuery 2 branch is EOL and no longer maintained

For JS library this is not enough reason. There is no security impact and chrome-gnome-shell is not affected by any of 2.x bugs AFAIK.

> build should be considered since it is smaller

It's not an issue too since library is available localy. I doubt if it give any speedup also.


To be honest I'm not interested in such upgrade for the sake of such upgrade. We gain nothing usefull, but may hit new bugs.

However you may create PR and I will review it. If you will, keep in mind that sweettooth-api.js is running with extensions.gnome.org version of JQuery. Otherwise this is WONTFIX.
