### ISSUE TITLE
Extension says updates available while on current master

### ISSUE THREAD

**Issue by xbonio** [nE0sIghT/chrome-gnome-shell-mirror#78]
Even though I have a gnome-shell extension updated to current master, the browser extension says it can be updated.
It happens a lot for [dash-to-dock](https://github.com/micheleg/dash-to-dock) so let's consider this one.

`~/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/metadata.json` says the shell extension version is: `c6c56866e6120c30a36a23f2ff630a2f90f925b0` what the browser extension considers as a version *behind* for some reason.

The workaround could be to manually set the version to `-1` in the .json file.

**Comment by nE0sIghT** [comment]
> what the browser extension considers as a version behind for some reason.

And this is competely right.

What do you thinking is wrong here?

**Comment by nE0sIghT** [comment]
To be clear: "version" of extension in metadata.json is autogenerated value by extensions.gnome.org.
GNOME Shell extensions update check is performed against extensions.gnome.org repository.

You did get extension from 3rd party resource (git whatever) and checking it's version (not numeric even!) against one at extensions.gnome.org.

Resulting behavior is completely undefined.

**Comment by xbonio** [comment]
Well, I disagree on that it's completely right. 
You can't get any newer version than current master, can you?

**Comment by nE0sIghT** [comment]
> Well, I disagree on that it's completely right.

You are just doing wrong things that's why you got undefined behavior.

Take latest version from e.g.o. OR do not use update check feature because it's not designed (and will never be) for outside-of-repository extensions - that's way you will get expected behavior.

> You can't get any newer version than current master, can you?

Version of *what*?
On the one side - extensions repository.
On the other side - non-repository extension.

Do not use extensions repository (update check feature) OR use extensions from repository only.

Anyway - how do you expect this is should work ever?

**Comment by xbonio** [comment]
> Version of what?
Of any repository.

> Anyway - how do you expect this is should work ever?
Maybe there's a chance to detect if version is set to a commit hash and skip update checking or mute pings at least?
I think many people uses non-repository extensions though.

**Comment by nE0sIghT** [comment]
> Of any repository.

No no no.
GNOME Shell integration works with extensions.gnome.org repository only.
You may set version to something like "version for my lovely wife" or "c2f7b0" - both cases integration will recognize version as "non repository" and advice you to install repository version.

> Maybe there's a chance to detect if version is set to a commit hash and skip update checking or mute pings at least?
> I think many people uses non-repository extensions though.

You are free to use any version of extensions - from e.g.o. or any other.
However you can not expect that checking updates through repository will somehow detect any git, svn or other versions and magicaly determine if it is outdated.

E.g. if you are using Debian. You may install rpm package manager. You may install any rpm package.
However you will never expect that deb will handle rpm packages or wise versa.

Ok, so in your case there are several options:
1. Stop checking updates through extensions.gnome.org repository. There is switch for it in integration options.
Really, you do not using this repository, so do not expect it will correctly works for you.
2. Fix "version" in extension metadata. Version should be set by extensions.gnome.org only. It's:
* numeric;
* autogenerated;
* consistent.

Therefore there is nothing to do for me. If you can suggest better solution - create PR.

**Comment by afontenot** [comment]
I was going to file a bug on exactly this issue, but decided to comment here since the idea was previously rejected. I have several extensions that are installed via the Arch Linux repo. I also have several installed from e.g.o. Given that this extension is capable of identifying the former as "system extensions", couldn't there be an option to stop checking for updates to system extensions (and hide the green update button), while still checking for updates to the other extensions? This seems like a reasonable compromise and would solve both my and the OP's issues.

**Comment by nE0sIghT** [comment]
@afontenot 

Your issue is not same as current because you are talking about system extensions only.
As I remember there is feature request exists for such option at b.g.o. already, however I may be wrong.
Anyway I agree that this options will be usefull.

**Comment by nE0sIghT** [comment]
@afontenot 

> stop checking for updates to system extensions

For what I see updates of system extensions is not checked currently.
It was disabled in commit 8e7347d6 that got into version 8.

Feel free to open new issue if it's not true for you.
