### ISSUE TITLE
Support newer firefox version

### ISSUE THREAD

**Issue by genofire** [nE0sIghT/chrome-gnome-shell-mirror#88]
![screenshot from 2018-03-19 08-21-47](https://user-images.githubusercontent.com/6905586/37582738-a4189a68-2b4e-11e8-8862-7d2efdfcf962.png)

**Comment by nE0sIghT** [comment]
I'm aware about this issue.
You can install version 10 manually [here](https://addons.mozilla.org/ru/firefox/addon/gnome-shell-integration/versions/) [1], however do not enable extensions synchronization because it is broken.

In several hours there will be released version 10.1 wich will support version 58+.

[1] https://addons.mozilla.org/ru/firefox/addon/gnome-shell-integration/versions/

**Comment by fteppe** [comment]
when I try to download it it tells me it is not compatible with 59.0.1

**Comment by genofire** [comment]
@fteppe version 10, i think you try to use 10.0.1

**Comment by fteppe** [comment]
you are right I tried to download 10.0.1, but isn't 59 part of 58+ ? Since I have another problem with the version 10 I hope the new one would fix it.

**Comment by nE0sIghT** [comment]
> but isn't 59 part of 58+

I think you meant "52+". It's just addons site UI bug. Actually, it is "52.*" for version 10.0.1.

**Comment by fteppe** [comment]
Oh you are right, with you comment saying 10.1 would come out soon for 58 I mixed up the two I'm really sorry.

**Comment by nE0sIghT** [comment]
Version 10.1 published at a.m.o.
